// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBInNqAA8MW6IoAdIP6QSvBRa1lYFxQ48',
    appId: '1:513598221273:web:3951709f4bfeda2ba4c7c8',
    messagingSenderId: '513598221273',
    projectId: 'lawlink-ahsaan-project-2026',
    authDomain: 'lawlink-ahsaan-project-2026.firebaseapp.com',
    storageBucket: 'lawlink-ahsaan-project-2026.firebasestorage.app',
    measurementId: 'G-B42TPKBVY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpwn6ZIvnC70OLGN50LD1MM9S38VGUUgM',
    appId: '1:513598221273:android:7a8736df7c24b4fca4c7c8',
    messagingSenderId: '513598221273',
    projectId: 'lawlink-ahsaan-project-2026',
    storageBucket: 'lawlink-ahsaan-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLKt4TtiMNXSAWzzYYwyi8iqaM60jL77Q',
    appId: '1:513598221273:ios:edc47ba9ef24520ea4c7c8',
    messagingSenderId: '513598221273',
    projectId: 'lawlink-ahsaan-project-2026',
    storageBucket: 'lawlink-ahsaan-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.ahsaanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLKt4TtiMNXSAWzzYYwyi8iqaM60jL77Q',
    appId: '1:513598221273:ios:edc47ba9ef24520ea4c7c8',
    messagingSenderId: '513598221273',
    projectId: 'lawlink-ahsaan-project-2026',
    storageBucket: 'lawlink-ahsaan-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.ahsaanProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBInNqAA8MW6IoAdIP6QSvBRa1lYFxQ48',
    appId: '1:513598221273:web:d33ab2516debe1e8a4c7c8',
    messagingSenderId: '513598221273',
    projectId: 'lawlink-ahsaan-project-2026',
    authDomain: 'lawlink-ahsaan-project-2026.firebaseapp.com',
    storageBucket: 'lawlink-ahsaan-project-2026.firebasestorage.app',
    measurementId: 'G-R34EKWKG8H',
  );
}
